brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListView,
    TodoDetailView,
    TodoCreateView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="todos_list"),
    path("<int:pk>/", TodoDetailView.as_view(), name="show_todolist"),
    path("new/", TodoCreateView.as_view(), name="create_todolist"),
]

todos/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField()
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from operator import mod
from pyexpat import model
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from todos.models import TodoList
from django.views.generic.edit import CreateView

# Create your views here.
class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

todos/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Recipe - Scrumptious</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <main>
        <div>
            <h1>{{ todolist.name }}</h1>
            <h2>Tasks</h2>
            <table>
                <thead>
                    <tr>
                        <th colspan="2">Name</th>
                        <th>Due date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo_list in todolist_list %}
                    <tr>
                        <td>{{ todo_list.task }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>

</body>

</html>

todos/templates/todos/list.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>My Lists</h1>
        <table>
            <a href="{% url 'todos_list' %}">{{ todo_list.name }}</a>
            <thead>
                <tr>
                    <th colspan="2">Name</th>
                    <th>Number of items</th>
                </tr>
            </thead>
            <tbody>
                {% for todo_list in todolist_list %}
                <tr>
                    <td>{{ todo_list.name }}</td>
                    <td></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock content %}

todos/templates/todos/new.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Create a new list</h1>

    </div>
</main>
{% endblock content %}